after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - 1.11.x
install:
  - go get -v ./...
language: go
script:
  - go test -v -race -timeout=1m ./...
  - go test -v -timeout=1m -cover -coverprofile=coverage.out ./...
